add_entrypoint_object(
  regcomp
  SRCS
    tre/regcomp.c
    tre/tre-mem.c
  HDRS
    regcomp.h
    tre/tre.h
  DEPENDS
    libc.include.regex
    libc.include.wchar
    libc.include.wctype
    libc.include.stdlib
    libc.include.string
    libc.include.limits
    libc.include.stdint
    libc.include.ctype
    libc.include.assert
    libc.hdr.types.regex_t
    libc.hdr.regex_macros
  COMPILE_OPTIONS
    -Wno-implicit-fallthrough
    -Wno-covered-switch-default
)

add_entrypoint_object(
  regexec
  SRCS
    tre/regexec.c
  HDRS
    regexec.h
    tre/tre.h
  DEPENDS
    libc.include.regex
    libc.include.wchar
    libc.include.wctype
    libc.include.stdlib
    libc.include.string
    libc.include.limits
    libc.include.stdint
    libc.hdr.types.regex_t
    libc.hdr.types.regmatch_t
    libc.hdr.types.size_t
    libc.hdr.regex_macros
  COMPILE_OPTIONS
    -Wno-sign-compare
)

add_entrypoint_object(
  regerror
  SRCS
    regerror.cpp
  HDRS
    regerror.h
  DEPENDS
    libc.hdr.types.regex_t
    libc.hdr.types.size_t
    libc.hdr.regex_macros
    libc.src.__support.common
    libc.src.__support.CPP.string_view
    libc.src.string.memory_utils.inline_memcpy
)

add_entrypoint_object(
  regfree
  ALIAS
  DEPENDS
    .regcomp
)

install(FILES tre/LICENSE.TRE DESTINATION share/licenses/llvm-libc)
